### ISSUE TITLE
Test Suite info and Failed Tests Detail no showing on Slack

### ISSUE THREAD

**Issue by fjlour** [test-results-reporter/reporter#146] opened 2024-02-22 15:55 UTC
Hello, first of all thanks for this tool, it looks very promising. However I can't seem to get the details about the Test Suites within the Slack message. Using 1.1.0.

I tried also with minimal config.json parameters, same result, no details.

Here's the resulting Message
<img width="627" alt="image" src="https://github.com/test-results-reporter/reporter/assets/42777078/28dda71c-6059-40ac-85e4-2fc590d9592b">

I was expecting to have Details about the Failed tests like the image shown in [your documentation](https://test-results-reporter.github.io/targets/slack.html).

![image](https://github.com/test-results-reporter/reporter/assets/42777078/fe97b0e7-5d77-4787-9136-6b1593aff328)

Here's a sample XML to exemplify the format we're using:
`<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Tests" tests="8" errors="0" failures="0" skipped="0" time="81.309" timestamp="2024-02-20T19:49:20.314845">
	<testsuite name="Authentication" tests="8" errors="0" failures="0" skipped="0" time="81.297" timestamp="2024-02-20T19:49:20.325798">
		<testsuite name="Authentication" tests="2" errors="0" failures="0" skipped="0" time="16.367" timestamp="2024-02-20T19:49:20.326778">
			<testcase classname="Tests.Authentication.Authentication" name="AUTHENTICATION_000: User is lead to authentication page with the correct language" time="4.732"></testcase>
			<testcase classname="Tests.Authentication.Authentication" name="AUTHENTICATION_001: User see error message with information that password should not exceed 200 chars" time="4.809"></testcase>
			<properties>
				<property name="Documentation" value="This suite aims to test authentication feature."/>
			</properties>
		</testsuite>
		<testsuite name="Invalid Credentials" tests="4" errors="0" failures="0" skipped="0" time="46.958" timestamp="2024-02-20T19:49:54.664177">
			<testcase classname="Tests.Authentication.Invalid Credentials" name="INVALID_CREDENTIALS_000" time="12.548"></testcase>
			<testcase classname="Tests.Authentication.Invalid Credentials" name="INVALID_CREDENTIALS_001" time="11.105"></testcase>
			<testcase classname="Tests.Authentication.Invalid Credentials" name="INVALID_CREDENTIALS_002" time="11.926">
				<properties>
					<property name="Documentation" value="This suite aims to test authentication feature with invalid credentials."/>
				</properties>
			</testsuite>
		</testsuite>
	</testsuite>`

**Comment by ASaiAnudeep** [comment] 2024-02-23 05:21
hey @fjlour , could you please share us the `config.json` file to help us investigate further.

**Comment by fjlour** [comment] 2024-02-23 10:03
Sure, here it is:
`{
    "reports": [
        {
            "targets": [
                {
                    "name": "slack",
                    "inputs": {
                        "url": "{SLACK_CHANNEL_URL}",
                        "publish": "failure-details",
                        "title": "{SLACK_TITLE}",
                        "title_link": "{SLACK_TITLE_URL}",
                        "_title_suffix": "{SLACK_TITLE_SUFFIX}"

                    },
                    "extensions": [
                    {
                        "name": "hyperlinks",
                        "condition": "passOrFail",
                        "inputs": {
                            "links": [
                            {
                                    "text": "Test Results",
                                    "url": "{SLACK_TEST_RESULTS_URL}"
                            }
                            ]
                        }
                    },
                    {
                        "name": "metadata",
                        "inputs": {
                          "data": [
                            {
                                "key": "Environment",
                                "value": "{SLACK_META_TARGET_ENV}"
                            },
                            {
                                "key": "Target Version",
                                "value": "{SLACK_META_TARGET_VERSION}"
                            },
                            {
                                "key": "Tests Source",
                                "value": "{SLACK_META_TESTS_SOURCE}"
                            }
                          ]
                        }
                    },
                    {
                        "name": "quick-chart-test-summary"
                    }
                    ]
                }
            ],
            "results": [
                {
                    "type": "junit",
                    "files": [
                        "xunit.xml"
                    ]
                }
            ]
        }
    ]
}
`

**Comment by sylbn** [comment] 2024-03-22 08:04
Hello,

I had a similar issue but not exactly the same.
I had details on only the first 10 tests if there were failed, with the parameter only_failures: true

I saw that a new parameter max_suites has been added the 3 march, when our notification start to not work.
The default value of max_suites is set to 10.

I don't know exactly how this parameter is intended to work, but in our case details are displayed only if one of the 10 first tests are failed.

So as a workaround, I modified this parameter max_suites: 100 and it worked.

But I was expecting that the 10 first tests failed were displayed (with max_suites:10) ?

Hope it helps

**Comment by ASaiAnudeep** [comment] 2024-03-22 10:49
@fjlour I'm able to get the failure details in the slack report. I'm using the latest version of the tool.

<img width="638" alt="Screenshot 2024-03-22 at 16 16 25" src="https://github.com/test-results-reporter/reporter/assets/20973632/16823026-b297-442f-bf4e-ed33c668d90e">

**Comment by ASaiAnudeep** [comment] 2024-03-31 06:52
Closing this as not reproducible. Feel free to restart the conversation.

**Closed by ASaiAnudeep** 2024-03-31 06:52 UTC
